### ISSUE TITLE
Bump-up to 'haskell-src-exts-1.20.1' (also support build with stack)

### ISSUE THREAD

**Issue by ChShersh** [haskell-suite/haskell-names#103]
`haskell-names` disappeared from _Stackage_

* https://www.stackage.org/nightly-2017-12-27

This happened during this action:

* https://www.snoyman.com/blog/2017/12/dropped-packages-following-lts-10

As a consequence, `importify` project which I'm working on also was dropped from _Stackage_ snapshot. It would be good to return `haskell-names` back to _Stackage_.

**Comment by ChShersh** [comment]
@phischu I've merged PR #105. Could you please upload `haskell-names-0.9.1` to Hackage? Or you could make me a maintainer of `haskell-names` (so I can upload it as well). My username:

* http://hackage.haskell.org/user/shersh

**Comment by phischu** [comment]
I made you a maintainer on hackage. Feel free to upload a new version.
