### ISSUE TITLE
HsFFI.h isn't found when using hs-gen-iface

### ISSUE THREAD

**Issue by rhymoid** [haskell-suite/haskell-names#44]
ζ: ~/.cabal/bin/cabal install primitive --haskell-suite -w hs-gen-iface  
    Resolving dependencies...
    Configuring primitive-0.5.1.0...
    cabal: Missing dependency on a foreign library:
    * Missing (or bad) header file: primitive-memops.h
    This problem can usually be solved by
    [...]
    the error messages.
    Failed to install primitive-0.5.1.0
    cabal: Error: some packages failed to install:
    primitive-0.5.1.0 failed during the configure step. The exception was:
    ExitFailure 1

When running with -v3, we see that `HsFFI.h` isn't found:

    ("/usr/bin/gcc",["/tmp/17376.c","-o","/tmp/17376","-D__HASKELL_SUITE__","-Dlinux_HOST_OS=1","-Dx86_64_HOST_ARCH=1","-Idist/build/autogen","-Icbits","-I.","-O3","-ftree-vectorize","-fomit-frame-pointer","-msse2","-I/home/feuerbach/.cabal/lib/i386-linux-haskell-names-0.2/base-4.7.0.0/include","-O3","-ftree-vectorize","-fomit-frame-pointer","-msse2","-L/home/stijn/.cabal/share/x86_64-linux-ghc-7.6.3/haskell-names-0.3.1/libraries/base-4.7.0.0","-L/home/stijn/.cabal/share/x86_64-linux-ghc-7.6.3/haskell-names-0.3.1/libraries/integer-simple-0.1.1.0","-L/home/stijn/.cabal/share/x86_64-linux-ghc-7.6.3/haskell-names-0.3.1/libraries/ghc-prim-0.3.1.0"])
    /usr/bin/gcc returned ExitFailure 1 with error message:
    In file included from /tmp/17376.c:1:0:
    cbits/primitive-memops.h:5:19: fatal error: HsFFI.h: No such file or directory
    #include <HsFFI.h>
    ^
    compilation terminated.

This problem doesn't occur during normal use of cabal-install. `--extra-include-dirs=/usr/lib/ghc/include` is a quick fix to the problem.

**Comment by phischu** [comment]
Going forward I want to remove the dependency on haskell-packages and support for hs-gen-iface. Sorry.
