### ISSUE TITLE
Add haskell-names back to stackage

### ISSUE THREAD

**Issue by niteria** [haskell-suite/haskell-names#74]
I was able to build `haskell-names` with the latest (GHC 8 based) `stackage` nightly after relaxing version bounds on `aeson` and `transformers`. Can you make a new release with relaxed bounds and add it to stackage?

**Comment by phischu** [comment]
How do I add it back to stackage?

**Comment by niteria** [comment]
You just send a pull request to this file
https://github.com/fpco/stackage/blob/master/build-constraints.yaml

**Comment by phischu** [comment]
Ok, see https://github.com/fpco/stackage/pull/1732

**Comment by niteria** [comment]
Thank you!
