### ISSUE TITLE
Overlapping instances for GTraversable

### ISSUE THREAD

**Issue by ciez** [haskell-suite/haskell-names#84]
is it possible to define own instances of GTraversable that do not overlap with haskell-names derived instances? e.g.

```
instance GTraversable (Process m) (Module l) where ...

class Process s a where 
    upd::a -> State s a
```

own instances seem to work ok before haskell-names lib is added to project. Once haskell-names is added, instances overlap.

I may be doing it incorrectly of course. Could you please confirm if this is possible to define own GTraversable instances in the same project?

**Comment by phischu** [comment]
No, sadly [this module](https://github.com/haskell-suite/haskell-names/blob/67f54096e8732697a54cdb25c2d1f74b39ccabaf/src/Language/Haskell/Names/Open/Derived.hs) derives intances of `GTraversable` that overlap with your instances.
