### ISSUE TITLE
Please, release 0.9.0 version

### ISSUE THREAD

**Issue by ChShersh** [haskell-suite/haskell-names#99]
This version contains important bug fixes for records. It would be good to have it released, at least on _Hackage_, but better on _Stackage_.

**Comment by phischu** [comment]
Ok, [released](https://hackage.haskell.org/package/haskell-names-0.9.0). This release is compatible with Stackage LTS 9.4 so I'll readd it there. Thank you for your encouragement. Do you want to become a maintainer?

**Comment by ChShersh** [comment]
@phischu That would be great! Thank you for writing such amazing library :)
